# .kodiak.toml
version = 1

[merge]
require_automerge_label = false # merge everything
method = "squash"
delete_branch_on_merge = true
block_on_reviews_requested = true
optimistic_updates = true
prioritize_ready_to_merge = true
notify_on_conflict = false

[merge.message]
title = "pull_request_title"
body = "pull_request_body"
include_coauthors= true
include_pr_number = true
body_type = "markdown"
strip_html_comments = true
