version: "3.9"

networks:
  # Network for api gateway
  network-gateway:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.2.0/24

  # Network for microservices
  network-microservice:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.4.0/24

services:
  reaction_db:
    container_name: reaction_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: reaction_db
      CI: true
    ports:
      - "5432:5432"
    networks:
      - network-microservice

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      CI: true
    ports:
      - "5050:80"
    networks:
      - network-microservice

  consul:
    container_name: consul
    image: consul
    restart: on-failure
    environment:
      NODE_ENV: development
      CI: true
    volumes:
      - consul-data:/consul/config
    ports:
      - "8500:8500"
    networks:
      - network-microservice

  reaction_apis:
    container_name: reaction_apis
    image: apis-reaction:latest
    restart: unless-stopped
    hostname: reaction_apis
    build:
      context: .
      dockerfile: apps/apis/reaction/Dockerfile
    environment:
      NODE_ENV: development
      CI: true
    networks:
      - network-microservice
    links:
      - reaction_db
      - consul
    depends_on:
      - reaction_db
      - consul

  gateway:
    container_name: gateway
    image: apis-gateway:latest
    restart: unless-stopped
    environment:
      NODE_ENV: development
      CI: true
    build:
      context: .
      dockerfile: apps/apis/gateway/Dockerfile
    ports:
      - "8080:80"
    networks:
      - network-gateway
      - network-microservice
    links:
      - reaction_apis
      - consul
    depends_on:
      - consul

volumes:
  consul-data:
