version: "3.9"

networks:
  # Network for microservices
  network-microservice:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.4.0/24
  network-eventstore:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.6.0/24

services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    networks:
      - network-microservice
    volumes:
      - pgadmin-data:/root/.pgadmin
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
    deploy:
      restart_policy:
        condition: always
        delay: 5s

  reaction.write-db:
    container_name: reaction.write-db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - network-microservice
    volumes:
      - write-data:/var/lib/postgresql/data
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
    deploy:
      restart_policy:
        condition: always
        delay: 5s

  #reaction.read-db:
  #  container_name: reaction.read-db
  #  image: postgres
  #  restart: always
  #  ports:
  #    - 5434:5432
  #  volumes:
  #    - read-data:/var/lib/postgresql/data
  #  environment:
  #    ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
  #  deploy:
  #    restart_policy:
  #      condition: always
  #      delay: 5s

volumes:
  pgadmin-data:
  write-data:
  read-data:
