version: "3.9"

networks:
  # Network for microservices
  network-microservice:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.4.0/24
  network-eventstore:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.6.0/24

services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    networks:
      - network-microservice
    volumes:
      - pgadmin-data:/root/.pgadmin
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}

  reaction.write-db:
    container_name: reaction.write-db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - network-microservice
    volumes:
      - write-data:/var/lib/postgresql/data
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}

  reaction.read-db:
    container_name: reaction.read-db
    image: postgres
    restart: always
    ports:
      - "5434:5432"
    networks:
      - network-microservice
    volumes:
      - read-data:/var/lib/postgresql/data
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}

 # reaction.snapshot-db:
   # container_name: reaction.snapshot-db
   # image: redis:alpine
  #  restart: always
   # ports:
   #   - "5430:6379"
  #  networks:
   #   - network-microservice
  #  volumes:
   #   - snapshot-data:/data
  #  environment:
  #    ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}

volumes:
  pgadmin-data:
  write-data:
  read-data:
  #snapshot-data:
  #  driver: local
