version: "3.9"

networks:
  # Network for microservices
  network-microservice:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.4.0/24
  network-eventstore:
        driver: bridge

services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    networks:
      - network-microservice
    volumes:
      - pgadmin-data:/root/.pgadmin

  contact.db:
    container_name: contact.db
    image: postgres
    restart: always
    ports:
      - "5434:5432"
    networks:
      - network-microservice
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  reaction.db:
    container_name: reaction.db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - network-microservice
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  #######################################################
  #  EventStoreDB
  #######################################################
  eventstore.db:
    container_name: eventstore.db
    image: eventstore/eventstore
    ports:
        - "1113:1113"
        - "2113:2113"
    networks:
        - network-eventstore
    volumes:
        - type: volume
          source: eventstore-volume-data
          target: /var/lib/eventstore
        - type: volume
          source: eventstore-volume-logs
          target: /var/log/eventstore

volumes:
  postgresql-data:
  pgadmin-data:
  eventstore-volume-data:
  eventstore-volume-logs:
