version: "3.9"

networks:
  # Network for microservices
  network-microservice:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.4.0/24

services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    networks:
      - network-microservice
    volumes:
      - pgadmin-data:/root/.pgadmin

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    restart: always
    ports:
      - "5634:5634"
      - "5672:5672"
      - "15672:15672"
    networks:
      - network-microservice

  static.cache:
    container_name: static.cache
    image: redis:alpine
    restart: on-failure
    ports:
      - "5430:80"
    networks:
      - network-microservice

  contact.db:
    container_name: contact.db
    image: postgres
    restart: always
    ports:
      - "5434:5432"
    networks:
      - network-microservice
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  reaction.db:
    container_name: reaction.db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - network-microservice
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  postgresql-data:
  pgadmin-data:
