module.exports = {
  plugins: [require("prettier-plugin-tailwindcss")],
  trailingComma: "es5",
  tabWidth: 2,
  semi: true,
  singleQuote: false,
  quoteProps: "preserve",
  insertPragma: false,
  bracketSameLine: true,
  printWidth: 80,
  bracketSpacing: true,
  arrowParens: "avoid",
  endOfLine: "crlf",
  insertFinalNewline: false,
};
