name="contact-attachments-upload"
main="src/index.ts"

route="https://my-worker.open-system.workers.dev/api/contact/attachments/upload"

account_id="03700f13b61493bbc558dc93ea4980bc"
workers_dev=true

[build]
command="nx run worker-contact-attachments-upload:build:production"

[[r2_buckets]]
binding="CONTACT_ATTACHMENTS_BUCKET"
bucket_name="contact-attachments"
