name: 🎁 Feature Request
description: Suggest a new feature.
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - sullivanpj
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
        Use this issue type for concrete suggestions, otherwise, open a discussion type issue instead.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is the behavior that you would like to see introduced?
      placeholder: What is the behavior that you would like to see introduced?
      value: "What is the behavior that you would like to see introduced?"
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why do you believe this behavior would be beneficial?
      placeholder: Why do you believe this behavior would be beneficial?
      value: "Why do you believe this behavior would be beneficial?"
    validations:
      required: false
  - type: textarea
    id: implementation
    attributes:
      label: Suggested Implementation
      description: How do you imagine this might work?
      placeholder: How do you imagine this might work?
      value: "How do you imagine this might work?"
    validations:
      required: false
  - type: checkboxes
    id: contribute
    attributes:
      label: Contribution
      description: Willingness to contribute
      options:
        - label: I'd be willing to implement this feature ([contributing guide](https://github.com/stormstack/stormstack/blob/main/CONTRIBUTING.md))
          required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this request, you agree to follow our [Code of Conduct](https://github.com/stormstack/stormstack/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
