name = "<%= name %>"
main = "src/index.ts"
assets="../../../dist/apps/workers/<%= name %>"

latest = true
route = "open-system.io/api<%= route %>"

compatibility_date = "<%= compatibility_date %>"

account_id = "<%= account_id %>"
workers_dev = true

[build]
command = "nx run worker-<%= name %>:build"


