---
version: "3.9"

services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    volumes:
      - pgadmin-data:/root/.pgadmin
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
    deploy:
      restart_policy:
        condition: always
        delay: 5s

  reaction.write-db:
    container_name: reaction.write-db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - write-data:/var/lib/postgresql/data
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
    deploy:
      restart_policy:
        condition: always
        delay: 5s

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    deploy:
      restart_policy:
        condition: always
        delay: 5s

  kafka-broker:
    image: confluentinc/cp-enterprise-kafka:latest
    hostname: kafka-broker
    container_name: kafka-broker
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9997:9997
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://kafka-schema-registry:8081
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      CONNECT_CONFLUENT_TOPIC_REPLICATION_FACTOR: 1
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka-broker:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: true
      CONFLUENT_SUPPORT_CUSTOMER_ID: "OpenSystem"
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: kafka-broker
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    deploy:
      restart_policy:
        condition: always
        delay: 5s

  kafka-schema-registry:
    image: confluentinc/cp-schema-registry:latest
    hostname: kafka-schema-registry
    container_name: kafka-schema-registry
    depends_on:
      - kafka-broker
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: kafka-schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka-broker:29092'
      SCHEMA_REGISTRY_LISTENERS: http://kafka-schema-registry:8081
    deploy:
      restart_policy:
        condition: always
        delay: 5s

  ksqldb-server:
    image: confluentinc/cp-ksqldb-server:latest
    hostname: ksqldb-server
    container_name: ksqldb-server
    depends_on:
      - kafka-broker
      - kafka-schema-registry
    ports:
      - 8088:8088
    environment:
      KSQL_CONFIG_DIR: "/etc/ksql"
      KSQL_HOST_NAME: ksqldb-server
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_BOOTSTRAP_SERVERS: 'kafka-broker:29092'
      KSQL_KSQL_SCHEMA_REGISTRY_URL: http://kafka-schema-registry:8081
      KSQL_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
      KSQL_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
      KSQL_KSQL_CONNECT_URL: "http://kafka-connect:8083"
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: true
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: true
      KSQL_CACHE_MAX_BYTES_BUFFERING: 0
    deploy:
      restart_policy:
        condition: always
        delay: 5s

  ksqldb-cli:
    image: confluentinc/cp-ksqldb-cli:latest
    container_name: ksqldb-cli
    depends_on:
      - kafka-broker
      - ksqldb-server
    entrypoint: /bin/sh
    tty: true
    deploy:
      restart_policy:
        condition: always
        delay: 5s

  kafka-connect:
    image: cnfldemos/kafka-connect-datagen:0.6.0-7.3.0
    hostname: kafka-connect
    container_name: kafka-connect
    depends_on:
      - kafka-broker
      - kafka-schema-registry
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'kafka-broker:29092'
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://kafka-schema-registry:8081
      CONNECT_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
      CONNECT_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
      CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR
    deploy:
      restart_policy:
        condition: always
        delay: 5s

  kafka-control-center:
    image: confluentinc/cp-enterprise-control-center:latest
    hostname: kafka-control-center
    depends_on:
      - zookeeper
      - kafka-broker
      - kafka-schema-registry
      - kafka-connect
      - ksqldb-server
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka-broker:29092'
      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://kafka-schema-registry:8081"
      CONTROL_CENTER_CONNECT_CONNECT-DEFAULT_CLUSTER: 'kafka-connect:8083'
      CONTROL_CENTER_KSQL_KSQLDB1_URL: "http://ksqldb-server:8088"
      CONTROL_CENTER_KSQL_KSQLDB1_ADVERTISED_URL: "http://localhost:8088"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONTROL_CENTER_SCHEMA_REGISTRY_ENABLE: true
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021
    deploy:
      restart_policy:
        condition: always
        delay: 5s

volumes:
  pgadmin-data:
  write-data:
  read-data:

  #KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schemaregistry:8085
  #KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: first
  #KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect:8083

  # reaction.read-db:
  #  container_name: reaction.read-db
  #  image: redis:alpine
  #  restart: always
  #  ports:
  #    - "5430:6379"
  #  networks:
  #    - network-microservice
  #  volumes:
  #    - read-data:/data
  #  environment:
  #    ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}


  #snapshot-data:
  #  driver: local


  # reaction.read-db:
  #  container_name: reaction.read-db
  #  image: postgres
  #  restart: always
  #  ports:
  #    - "5434:5432"
  #  networks:
  #    - network-microservice
  #  volumes:
  #    - read-data:/var/lib/postgresql/data
  #  environment:
  #    ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}

  #zookeeper:
  #  image: confluentinc/cp-zookeeper:latest
  #  container_name: zookeeper
  #  networks:
  #   - network-microservice
  #  ports:
  #    - 2181:2181
  #  environment:
  #    ZOOKEEPER_CLIENT_PORT: 2181
  #    ZOOKEEPER_TICK_TIME: 2000

  #kafka:
  #  image: confluentinc/cp-kafka:latest
  #  container_name: kafka
  #  networks:
  #   - network-microservice
  #  depends_on:
  #    - zookeeper
  #  ports:
  #    - 9092:9092
  #  environment:
  #    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #    KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
  #    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #    KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #    KAFKA_LOG_CLEANER_DELETE_RETENTION_MS: 5000
  #    KAFKA_BROKER_ID: 1
  #    KAFKA_MIN_INSYNC_REPLICAS: 1

 # kafka-ui:
 #   container_name: kafka-ui
 #   image: provectuslabs/kafka-ui:latest
 #   ports:
 #     - 8084:8080
 #   networks:
 #     - network-microservice
 #   environment:
 #     - KAFKA_CLUSTERS_0_NAME=network-microservice
 #     - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=PLAINTEXT://kafka:29092
    #  - KAFKA_CLUSTERS_0_SCHEMAREGISTRY=http://schema-registry:8081
    #  - KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME=debezium
    #  - KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS=http://debezium-connect:8083
  #  depends_on:
  #    - zookeeper
  #    - kafka
