/**
 * Engagement
 * A collection of APIs used to get and set user reactions and comments for an article/page
 *
 * OpenAPI spec version: 1.0
 * Contact: Patrick.Joseph.Sullivan@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ReactionDetail } from "./ReactionDetail";
import { HttpFile } from "@open-system/core-typescript-utilities";

export class GetArticleReactions200Response {
  /**
   * The `guid` associated with the record
   */
  "guid": string;
  "createdOn": Date;
  "createdBy": string;
  "updatedOn"?: Date;
  "updatedBy"?: string;
  /**
   * The id of the article/page
   */
  "articleId": string;
  /**
   * The list of reactions for the specified article
   */
  "reactions": Array<ReactionDetail>;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      "name": "guid",
      "baseName": "guid",
      "type": "string",
      "format": "uuid",
    },
    {
      "name": "createdOn",
      "baseName": "createdOn",
      "type": "Date",
      "format": "date-time",
    },
    {
      "name": "createdBy",
      "baseName": "createdBy",
      "type": "string",
      "format": "",
    },
    {
      "name": "updatedOn",
      "baseName": "updatedOn",
      "type": "Date",
      "format": "date-time",
    },
    {
      "name": "updatedBy",
      "baseName": "updatedBy",
      "type": "string",
      "format": "",
    },
    {
      "name": "articleId",
      "baseName": "articleId",
      "type": "string",
      "format": "",
    },
    {
      "name": "reactions",
      "baseName": "reactions",
      "type": "Array<ReactionDetail>",
      "format": "",
    },
  ];

  static getAttributeTypeMap() {
    return GetArticleReactions200Response.attributeTypeMap;
  }

  public constructor() {}
}
