/**
 * Engagement
 * A collection of APIs used to get and set user reactions and comments for an article/page
 *
 * OpenAPI spec version: 1.0
 * Contact: Patrick.Joseph.Sullivan@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from "@open-system/core-typescript-utilities";

/**
 * A response returned from the server when data is successfully updated
 */
export class UpdateSuccessResponse {
  /**
   * The `guid` associated with the record
   */
  "guid": string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      "name": "guid",
      "baseName": "guid",
      "type": "string",
      "format": "uuid",
    },
  ];

  static getAttributeTypeMap() {
    return UpdateSuccessResponse.attributeTypeMap;
  }

  public constructor() {}
}
