:: Generated by: https://openapi-generator.tech
::

@echo off

dotnet restore
dotnet build
echo Now, run the following to start the project: dotnet run -p OpenSystem.Apis.User.csproj --launch-profile web.
echo.
