/**
 * User APIs
 * A collection of APIs used to get and set user related data 
 *
 * OpenAPI spec version: 1
 * Contact: Patrick.Joseph.Sullivan@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  HttpFile,
} from '@open-system/core-typescript-utilities';


export class UpdateUserRequestDto {
    'name': string;
    'type': UpdateUserRequestDtoTypeDtoEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "UpdateUserRequestDtoTypeDtoEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateUserRequestDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export type UpdateUserRequestDtoTypeDtoEnum = "guest" | "internal" | "external" ;

