/* eslint-disable @typescript-eslint/no-unused-vars */
import {
  CustomFileHeadersBuilder,
  ExtensionContext
} from "@nxkit/style-dictionary/extensions";

const customFileHeadersBuilder: CustomFileHeadersBuilder = (
  _: ExtensionContext
) => {
  return {
    myCustomHeader: function (defaultMessage) {
      return [
        `
******************************************************************
*
*                         Open System
*                  ⚡Impact - Design System⚡
*
*                 ** DO NOT MODIFY THIS FILE **
* This file is automatically generated by ⚡Impact Generate
* (built with style-dictionary) and should not be manually
* updated. Any changes made to this file will be overwritten
* the next time the design tokens are generated.
*
* Repository: https://github.com/stormstack/stormstack
* Documentation: https://stormstack.github.io/stormstack/
* Contact: https://patsullivan.org/contact
*
******************************************************************

`,
        ...defaultMessage
      ];
    }
  };
};

export default customFileHeadersBuilder;
