/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SelectOption } from "./components/os-select/os-select.types";
export namespace Components {
    interface OsButton {
        /**
          * Is the button read-only (cannot be clicked by user)
         */
        "disabled": boolean;
        /**
          * Is the button filled by default
         */
        "inverse": boolean;
        /**
          * The direction the hover animation will start on
         */
        "transitionDirection": string;
        /**
          * Is the button filled by default
         */
        "type": string;
        /**
          * The variant style of the button
         */
        "variant": string;
    }
    interface OsCard {
        /**
          * The first name
         */
        "header": string;
        /**
          * The middle name
         */
        "imageSrc": string;
        /**
          * The last name
         */
        "summary": string;
    }
    interface OsCheckbox {
        /**
          * Decides if input is disabled
         */
        "disabled": boolean;
        /**
          * An info message displayed under the input
         */
        "info"?: string;
        /**
          * The text label displayed above the input field
         */
        "label": string;
        /**
          * The name of the input field
         */
        "name": string;
        /**
          * Should the border displayed on the left side of the input field remain hidden
         */
        "noBorder": boolean;
        /**
          * Decides if input field required
         */
        "required": boolean;
    }
    interface OsHeader {
        /**
          * The level of the header
          * @example h1, h2, h3, h4, h5, h6, etc.
         */
        "level": number;
    }
    interface OsInput {
        /**
          * Decides if input is disabled
         */
        "disabled": boolean;
        /**
          * An info message displayed under the input
         */
        "info"?: string;
        /**
          * The text label displayed above the input field
         */
        "label": string;
        /**
          * The maximum input value allowed
         */
        "max"?: number;
        /**
          * The maximum allowed input length value of the field
         */
        "maxLength"?: number;
        /**
          * The minimum input value allowed
         */
        "min"?: number;
        /**
          * The minimum allowed input length value of the field
         */
        "minLength"?: number;
        /**
          * The name of the input field
         */
        "name": string;
        /**
          * Should the border displayed on the left side of the input field remain hidden
         */
        "noBorder": boolean;
        /**
          * A regular expression pattern, such as [A-Z]+ for one or more uppercase characters
         */
        "pattern"?: string;
        /**
          * Placeholder text when the field value is empty
         */
        "placeholder"?: string;
        /**
          * Decides if input field required
         */
        "required": boolean;
        /**
          * Input select method
         */
        "selectText": () => Promise<void>;
        /**
          * Input error method
         */
        "setError": (error: string) => Promise<void>;
        /**
          * Input focus method
         */
        "setFocus": () => Promise<void>;
        /**
          * Input warning method
         */
        "setWarning": (warning: string) => Promise<void>;
        /**
          * Type of input
         */
        "type": string;
    }
    interface OsLink {
        /**
          * Is the link selected
         */
        "selected": boolean;
    }
    interface OsNumberInput {
        /**
          * Decides if input is disabled
         */
        "disabled": boolean;
        /**
          * An info message displayed under the input
         */
        "info"?: string;
        /**
          * The text label displayed above the input field
         */
        "label": string;
        /**
          * The maximum input value allowed
         */
        "max"?: number;
        /**
          * The minimum input value allowed
         */
        "min"?: number;
        /**
          * The name of the input field
         */
        "name": string;
        /**
          * Should the border displayed on the left side of the input field remain hidden
         */
        "noBorder": boolean;
        /**
          * Decides if input field required
         */
        "required": boolean;
        /**
          * Input select method
         */
        "selectText": () => Promise<void>;
        /**
          * Input error method
         */
        "setError": (error: string) => Promise<void>;
        /**
          * Input focus method
         */
        "setFocus": () => Promise<void>;
        /**
          * Input warning method
         */
        "setWarning": (warning: string) => Promise<void>;
    }
    interface OsSection {
        /**
          * The section header string
         */
        "header"?: string;
        /**
          * One or multiple tailwindcss height utility class(es)
         */
        "height"?: string;
        /**
          * One or multiple tailwindcss width utility class(es)
         */
        "width"?: string;
    }
    interface OsSelect {
        /**
          * Decides if input is disabled
         */
        "disabled": boolean;
        /**
          * An info message displayed under the input
         */
        "info"?: string;
        /**
          * The text label displayed above the input field
         */
        "label": string;
        /**
          * The maximum input value allowed
         */
        "max"?: number;
        /**
          * The maximum allowed input length value of the field
         */
        "maxLength"?: number;
        /**
          * The minimum input value allowed
         */
        "min"?: number;
        /**
          * The minimum allowed input length value of the field
         */
        "minLength"?: number;
        /**
          * The name of the input field
         */
        "name": string;
        /**
          * Should the border displayed on the left side of the input field remain hidden
         */
        "noBorder": boolean;
        /**
          * Type of input
         */
        "options": SelectOption[];
        /**
          * A regular expression pattern, such as [A-Z]+ for one or more uppercase characters
         */
        "pattern"?: string;
        /**
          * Placeholder text when the field value is empty
         */
        "placeholder"?: string;
        /**
          * Decides if input field required
         */
        "required": boolean;
        /**
          * Input error method
         */
        "setError": (error: string) => Promise<void>;
        /**
          * Input focus method
         */
        "setFocus": () => Promise<void>;
        /**
          * Input warning method
         */
        "setWarning": (warning: string) => Promise<void>;
    }
    interface OsTitle {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
export interface OsButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOsButtonElement;
}
export interface OsInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOsInputElement;
}
export interface OsNumberInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOsNumberInputElement;
}
export interface OsSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOsSelectElement;
}
declare global {
    interface HTMLOsButtonElement extends Components.OsButton, HTMLStencilElement {
    }
    var HTMLOsButtonElement: {
        prototype: HTMLOsButtonElement;
        new (): HTMLOsButtonElement;
    };
    interface HTMLOsCardElement extends Components.OsCard, HTMLStencilElement {
    }
    var HTMLOsCardElement: {
        prototype: HTMLOsCardElement;
        new (): HTMLOsCardElement;
    };
    interface HTMLOsCheckboxElement extends Components.OsCheckbox, HTMLStencilElement {
    }
    var HTMLOsCheckboxElement: {
        prototype: HTMLOsCheckboxElement;
        new (): HTMLOsCheckboxElement;
    };
    interface HTMLOsHeaderElement extends Components.OsHeader, HTMLStencilElement {
    }
    var HTMLOsHeaderElement: {
        prototype: HTMLOsHeaderElement;
        new (): HTMLOsHeaderElement;
    };
    interface HTMLOsInputElement extends Components.OsInput, HTMLStencilElement {
    }
    var HTMLOsInputElement: {
        prototype: HTMLOsInputElement;
        new (): HTMLOsInputElement;
    };
    interface HTMLOsLinkElement extends Components.OsLink, HTMLStencilElement {
    }
    var HTMLOsLinkElement: {
        prototype: HTMLOsLinkElement;
        new (): HTMLOsLinkElement;
    };
    interface HTMLOsNumberInputElement extends Components.OsNumberInput, HTMLStencilElement {
    }
    var HTMLOsNumberInputElement: {
        prototype: HTMLOsNumberInputElement;
        new (): HTMLOsNumberInputElement;
    };
    interface HTMLOsSectionElement extends Components.OsSection, HTMLStencilElement {
    }
    var HTMLOsSectionElement: {
        prototype: HTMLOsSectionElement;
        new (): HTMLOsSectionElement;
    };
    interface HTMLOsSelectElement extends Components.OsSelect, HTMLStencilElement {
    }
    var HTMLOsSelectElement: {
        prototype: HTMLOsSelectElement;
        new (): HTMLOsSelectElement;
    };
    interface HTMLOsTitleElement extends Components.OsTitle, HTMLStencilElement {
    }
    var HTMLOsTitleElement: {
        prototype: HTMLOsTitleElement;
        new (): HTMLOsTitleElement;
    };
    interface HTMLElementTagNameMap {
        "os-button": HTMLOsButtonElement;
        "os-card": HTMLOsCardElement;
        "os-checkbox": HTMLOsCheckboxElement;
        "os-header": HTMLOsHeaderElement;
        "os-input": HTMLOsInputElement;
        "os-link": HTMLOsLinkElement;
        "os-number-input": HTMLOsNumberInputElement;
        "os-section": HTMLOsSectionElement;
        "os-select": HTMLOsSelectElement;
        "os-title": HTMLOsTitleElement;
    }
}
declare namespace LocalJSX {
    interface OsButton {
        /**
          * Is the button read-only (cannot be clicked by user)
         */
        "disabled"?: boolean;
        /**
          * Is the button filled by default
         */
        "inverse"?: boolean;
        /**
          * Event emitted when the user clicks into the button
         */
        "onOsClick"?: (event: OsButtonCustomEvent<MouseEvent>) => void;
        /**
          * The direction the hover animation will start on
         */
        "transitionDirection"?: string;
        /**
          * Is the button filled by default
         */
        "type"?: string;
        /**
          * The variant style of the button
         */
        "variant"?: string;
    }
    interface OsCard {
        /**
          * The first name
         */
        "header"?: string;
        /**
          * The middle name
         */
        "imageSrc"?: string;
        /**
          * The last name
         */
        "summary"?: string;
    }
    interface OsCheckbox {
        /**
          * Decides if input is disabled
         */
        "disabled"?: boolean;
        /**
          * An info message displayed under the input
         */
        "info"?: string;
        /**
          * The text label displayed above the input field
         */
        "label"?: string;
        /**
          * The name of the input field
         */
        "name"?: string;
        /**
          * Should the border displayed on the left side of the input field remain hidden
         */
        "noBorder"?: boolean;
        /**
          * Decides if input field required
         */
        "required"?: boolean;
    }
    interface OsHeader {
        /**
          * The level of the header
          * @example h1, h2, h3, h4, h5, h6, etc.
         */
        "level"?: number;
    }
    interface OsInput {
        /**
          * Decides if input is disabled
         */
        "disabled"?: boolean;
        /**
          * An info message displayed under the input
         */
        "info"?: string;
        /**
          * The text label displayed above the input field
         */
        "label"?: string;
        /**
          * The maximum input value allowed
         */
        "max"?: number;
        /**
          * The maximum allowed input length value of the field
         */
        "maxLength"?: number;
        /**
          * The minimum input value allowed
         */
        "min"?: number;
        /**
          * The minimum allowed input length value of the field
         */
        "minLength"?: number;
        /**
          * The name of the input field
         */
        "name"?: string;
        /**
          * Should the border displayed on the left side of the input field remain hidden
         */
        "noBorder"?: boolean;
        /**
          * Event emitted when the user clicks out of the input field
         */
        "onOsBlur"?: (event: OsInputCustomEvent<FocusEvent>) => void;
        /**
          * Event emitted during a value in change the input field
         */
        "onOsChange"?: (event: OsInputCustomEvent<InputEvent>) => void;
        /**
          * Event emitted when the user clicks into the input field
         */
        "onOsFocus"?: (event: OsInputCustomEvent<FocusEvent>) => void;
        /**
          * Event emitted during a value in change the input field
         */
        "onOsInput"?: (event: OsInputCustomEvent<InputEvent>) => void;
        /**
          * A regular expression pattern, such as [A-Z]+ for one or more uppercase characters
         */
        "pattern"?: string;
        /**
          * Placeholder text when the field value is empty
         */
        "placeholder"?: string;
        /**
          * Decides if input field required
         */
        "required"?: boolean;
        /**
          * Type of input
         */
        "type"?: string;
    }
    interface OsLink {
        /**
          * Is the link selected
         */
        "selected"?: boolean;
    }
    interface OsNumberInput {
        /**
          * Decides if input is disabled
         */
        "disabled"?: boolean;
        /**
          * An info message displayed under the input
         */
        "info"?: string;
        /**
          * The text label displayed above the input field
         */
        "label"?: string;
        /**
          * The maximum input value allowed
         */
        "max"?: number;
        /**
          * The minimum input value allowed
         */
        "min"?: number;
        /**
          * The name of the input field
         */
        "name"?: string;
        /**
          * Should the border displayed on the left side of the input field remain hidden
         */
        "noBorder"?: boolean;
        /**
          * Event emitted when the user clicks out of the input field
         */
        "onOsBlur"?: (event: OsNumberInputCustomEvent<FocusEvent>) => void;
        /**
          * Event emitted during a value in change the input field
         */
        "onOsChange"?: (event: OsNumberInputCustomEvent<InputEvent>) => void;
        /**
          * Event emitted when the user clicks into the input field
         */
        "onOsFocus"?: (event: OsNumberInputCustomEvent<FocusEvent>) => void;
        /**
          * Event emitted during a value in change the input field
         */
        "onOsInput"?: (event: OsNumberInputCustomEvent<InputEvent>) => void;
        /**
          * Decides if input field required
         */
        "required"?: boolean;
    }
    interface OsSection {
        /**
          * The section header string
         */
        "header"?: string;
        /**
          * One or multiple tailwindcss height utility class(es)
         */
        "height"?: string;
        /**
          * One or multiple tailwindcss width utility class(es)
         */
        "width"?: string;
    }
    interface OsSelect {
        /**
          * Decides if input is disabled
         */
        "disabled"?: boolean;
        /**
          * An info message displayed under the input
         */
        "info"?: string;
        /**
          * The text label displayed above the input field
         */
        "label"?: string;
        /**
          * The maximum input value allowed
         */
        "max"?: number;
        /**
          * The maximum allowed input length value of the field
         */
        "maxLength"?: number;
        /**
          * The minimum input value allowed
         */
        "min"?: number;
        /**
          * The minimum allowed input length value of the field
         */
        "minLength"?: number;
        /**
          * The name of the input field
         */
        "name"?: string;
        /**
          * Should the border displayed on the left side of the input field remain hidden
         */
        "noBorder"?: boolean;
        /**
          * Event emitted when the user clicks out of the input field
         */
        "onOsBlur"?: (event: OsSelectCustomEvent<FocusEvent>) => void;
        /**
          * Event emitted during a value in change the input field
         */
        "onOsChange"?: (event: OsSelectCustomEvent<InputEvent>) => void;
        /**
          * Event emitted when the user clicks into the input field
         */
        "onOsFocus"?: (event: OsSelectCustomEvent<FocusEvent>) => void;
        /**
          * Event emitted during a value in change the input field
         */
        "onOsInput"?: (event: OsSelectCustomEvent<InputEvent>) => void;
        /**
          * Type of input
         */
        "options"?: SelectOption[];
        /**
          * A regular expression pattern, such as [A-Z]+ for one or more uppercase characters
         */
        "pattern"?: string;
        /**
          * Placeholder text when the field value is empty
         */
        "placeholder"?: string;
        /**
          * Decides if input field required
         */
        "required"?: boolean;
    }
    interface OsTitle {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "os-button": OsButton;
        "os-card": OsCard;
        "os-checkbox": OsCheckbox;
        "os-header": OsHeader;
        "os-input": OsInput;
        "os-link": OsLink;
        "os-number-input": OsNumberInput;
        "os-section": OsSection;
        "os-select": OsSelect;
        "os-title": OsTitle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "os-button": LocalJSX.OsButton & JSXBase.HTMLAttributes<HTMLOsButtonElement>;
            "os-card": LocalJSX.OsCard & JSXBase.HTMLAttributes<HTMLOsCardElement>;
            "os-checkbox": LocalJSX.OsCheckbox & JSXBase.HTMLAttributes<HTMLOsCheckboxElement>;
            "os-header": LocalJSX.OsHeader & JSXBase.HTMLAttributes<HTMLOsHeaderElement>;
            "os-input": LocalJSX.OsInput & JSXBase.HTMLAttributes<HTMLOsInputElement>;
            "os-link": LocalJSX.OsLink & JSXBase.HTMLAttributes<HTMLOsLinkElement>;
            "os-number-input": LocalJSX.OsNumberInput & JSXBase.HTMLAttributes<HTMLOsNumberInputElement>;
            "os-section": LocalJSX.OsSection & JSXBase.HTMLAttributes<HTMLOsSectionElement>;
            "os-select": LocalJSX.OsSelect & JSXBase.HTMLAttributes<HTMLOsSelectElement>;
            "os-title": LocalJSX.OsTitle & JSXBase.HTMLAttributes<HTMLOsTitleElement>;
        }
    }
}
