// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenSystem.Blog.Reaction.Application.Models
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;

	/// <summary>
	/// The types of possible reactions a user could have to content.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public enum ReactionTypes
	{
		Like,
		Dislike,
		Love,
		Happy,
		Sad,
		Laugh,
		Cry,
	}
}
