/**
 * Contact APIs
 * A collection of APIs used to get and set contact related data 
 *
 * OpenAPI spec version: 1
 * Contact: Patrick.Joseph.Sullivan@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ContactDetailRecord } from './ContactDetailRecord';
import {
  HttpFile,
} from '@open-system/core-typescript-utilities';


/**
* A full contact model including all of it's previously submitted details
*/
export class ContactRecord {
    /**
    * The `guid` associated with the record
    */
    'id': string;
    'createdOn': Date;
    'createdBy': string;
    'updatedOn'?: Date;
    'updatedBy'?: string;
    'firstName'?: string;
    'lastName'?: string;
    'phoneNumber'?: string;
    /**
    * The email address of the contact
    */
    'email': string;
    'isSubscribed': boolean;
    'addressLine1'?: string;
    'addressLine2'?: string;
    'city'?: string;
    'state'?: string;
    'countryCode'?: string;
    'postalCode'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "createdOn",
            "baseName": "createdOn",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedOn",
            "baseName": "updatedOn",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedBy",
            "baseName": "updatedBy",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string",
            "format": ""
        },
        {
            "name": "phoneNumber",
            "baseName": "phoneNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": "email"
        },
        {
            "name": "isSubscribed",
            "baseName": "isSubscribed",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "addressLine1",
            "baseName": "addressLine1",
            "type": "string",
            "format": ""
        },
        {
            "name": "addressLine2",
            "baseName": "addressLine2",
            "type": "string",
            "format": ""
        },
        {
            "name": "city",
            "baseName": "city",
            "type": "string",
            "format": ""
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string",
            "format": ""
        },
        {
            "name": "countryCode",
            "baseName": "countryCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "postalCode",
            "baseName": "postalCode",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ContactRecord.attributeTypeMap;
    }

    public constructor() {
    }
}

