# Simple workflow for deploying documentation to GitHub Pages
name: "Deploy Documentation"

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - "main"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  NX_DAEMON: false
  NX_VERBOSE_LOGGING: true
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}

jobs:
  deploy-docs:
    if: github.repository == 'sullivanpj/open-system' && github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: https://registry.npmjs.org/
          cache: 'npm'

      - name: Install Dependencies
        uses: nrwl/nx-set-shas@v3
      - run: npm install --no-frozen-lockfile --legacy-peer-deps

      - name: Prepare for build
        run: npm run build:tools-ci

      - name: Build website
        run: npx nx run docs:build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./dist/docs"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2


