name: "Greetings"

on: [pull_request_target, issues]

env:
  CI: true
  NX_DAEMON: false
  NX_VERBOSE_LOGGING: true
  GITHUB_ACTOR: "🤖 Storm Bot"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Thank you for your interest in this project! We will review this issue and reach out to you ASAP"
          pr-message: "We sincerely appreciate your effort/interest in contributing to this project. We will review this change and get back to you ASAP. Please feel free to reach out to the DEV team if you have any questions/comments."
