---
name: Sync labels

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml

env:
  CI: true
  NX_DAEMON: false
  NX_VERBOSE_LOGGING: true
  SKIP_ENV_VALIDATION: true
  GITHUB_ACTOR: "🤖 Open-System Bot"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  labels:
    name: ♻️ Sync labels
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3
      - name: 🚀 Run Label Syncer
        uses: micnncim/action-label-syncer@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
