name: "Pull Request"

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true
  NX_CLOUD_DISTRIBUTED_EXECUTION_AGENT_COUNT: 3
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}

jobs:
  main:
    name: Nx Cloud - Main Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: https://registry.npmjs.org/
          cache: 'npm'

      - name: Install dependencies
        run: npm install --no-frozen-lockfile --legacy-peer-deps

      - name: Get appropriate base and head commits for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'main'
      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"

      - name: Start CI Orchestrator
        run: npx nx-cloud start-ci-run

      - name: Prepare for build
        run: npm run build:tools-ci

      - name: Build Design Tokens
        run: npx nx run design-system-tokens:build:open-system

      # - name: Run Tests
      #  uses: nick-fields/retry@v2.8.3
      #  with:
      #    timeout_minutes: 5
      #    max_attempts: 3
      #    command: npx nx affected -t test --configuration=ci

      - name: Stop Agents
        run: npx nx-cloud stop-all-agents

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

  agents:
    name: Nx Cloud - Agents
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        agent: [1, 2, 3]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          registry-url: https://registry.npmjs.org/
          cache: 'npm'

      - name: Install dependencies
        run: npm install --no-frozen-lockfile --legacy-peer-deps

      - name: Start Nx Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          registry-url: https://registry.npmjs.org/
          cache: 'npm'

      - name: Install dependencies
        run: npm install --no-frozen-lockfile --legacy-peer-deps

      - name: Run prettier
        run: npm run format

