name: "Pull Request"

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true
  NX_CLOUD_DISTRIBUTED_EXECUTION_AGENT_COUNT: 3
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}

jobs:
  main:
    name: Nx Cloud - Main Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org/
          node-version-file: .github/.nvmrc
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install Dependencies
        uses: nrwl/nx-set-shas@v3
      - run: pnpm i

      - name: Get appropriate base and head commits for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: "main"
      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"

      #- name: Start CI Orchestrator
      #  run: npx nx-cloud start-ci-run

      - name: Prepare for build
        run: pnpm build:tools-ci

      - name: Build Design Tokens
        run: pnpm nx run design-system-tokens:build:open-system

      # - name: Run Tests
      #  uses: nick-fields/retry@v2.8.3
      #  with:
      #    timeout_minutes: 5
      #    max_attempts: 3
      #    command: npx nx affected -t test --configuration=ci

      #- name: Stop Agents
      #  run: npx nx-cloud stop-all-agents

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
